name: Deploy

on:
  push:
    branches:
      - master

jobs:
   Heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-app-ser-heroku" 
          heroku_email: "serin.ahmad@stu.najah.edu"
          usedocker: 1 
          
   Docker-hub:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v1
          - name: login to my DockerHub
            uses: docker/login-action@v1
            with:
             username: ${{ secrets.DOCK_USERNAME }}
             password: ${{ secrets.DOCK_PASSWORD }}
          - name: Build
            run: docker build -t Docker 
          - name: Tags
            run: |
             docker tag Docker ${{ secrets.DOCK_USERNAME }}/Docker:latest
          - name: Push
            run: |
             docker push ${{ secrets.DOCK_USERNAME }}/Docker:latest 
             
